user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: "@SiteBundle/Controller/"
    type: rest
    prefix: /api/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

